//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCA.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Control_de_asistenciaEntities : DbContext
    {
        public Control_de_asistenciaEntities()
            : base("name=Control_de_asistenciaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<mostrar_empleado_id_Result> mostrar_empleado_id(Nullable<int> id_empleado)
        {
            var id_empleadoParameter = id_empleado.HasValue ?
                new ObjectParameter("id_empleado", id_empleado) :
                new ObjectParameter("id_empleado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<mostrar_empleado_id_Result>("mostrar_empleado_id", id_empleadoParameter);
        }
    
        public virtual ObjectResult<SP_mostrar_empleados_Activos_Result> SP_mostrar_empleados_Activos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_mostrar_empleados_Activos_Result>("SP_mostrar_empleados_Activos");
        }
    
        public virtual ObjectResult<SP_mostrar_empleado_asistencia_Result> SP_mostrar_empleado_asistencia(Nullable<int> id_empleado)
        {
            var id_empleadoParameter = id_empleado.HasValue ?
                new ObjectParameter("id_empleado", id_empleado) :
                new ObjectParameter("id_empleado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_mostrar_empleado_asistencia_Result>("SP_mostrar_empleado_asistencia", id_empleadoParameter);
        }
    }
}
